config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get "workflow" => "workflow#index"
  get "workflow/start" => "workflow#start"
  get "workflow/stop" => "workflow#stop"
  get "workflow/info/:class" => "workflow#info",
      :as => "workflow_info",
      :constraints => {
        class: /[A-Z][A-Za-z]+/
      }
  get "workflow/activate/:class" => "workflow#activate",
      :as => "workflow_activate",
      :constraints => {
        class: /[A-Z][A-Za-z]+/
      }
  get "workflow/options/:class" => "workflow#options",
      :as => "workflow_options",
      :constrants => {
        class: /[A-Z][A-Za-z]+/
      }
  post "workflow/run/:class" => "workflow#run",
       :as => "workflow_run",
       :constraints => {
         class: /[A-Z][A-Za-z]+/
       }
  get "workflow/fetch" => "workflow#fetch"
  get "workflow/fetch_load" => "workflow#fetch_load"
  delete "workflow/:id" => "workflow#destroy", :as => :destroy_task
  get "workflow/:id/view/:template" => "workflow#view", :as => :view_task

  # Start off on the landing/dashboard page
  root to: "workflow#index"

  # Search/Browse page
  get "search" => "search#index"
  get "search/load" => "search#load"
  get "search/advanced" => "search#advanced"

  # Documents
  get "documents/:id/export" => "documents#export",
      :as => "documents_export",
      :constraints => {
        id: /.*/
      }

  # Datasets
  resources :datasets, except: :edit do
    collection { get "load" }
  end

  # User login routes
  devise_for :users, skip: [:sessions], controllers: { passwords: "passwords" }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post "users/sign_in" => "devise/sessions#create", :as => :user_session
    match "users/sign_out" => "devise/sessions#destroy",
          :as => :destroy_user_session,
          :via => Devise.mappings[:user].sign_out_via

    # User export manipulation
    get "users/export" => "users#export_create", :as => :user_export
    delete "users/export" => "users#export_delete", :as => ""

    # Redirect to the root after a successful user edit
    get "users" => "workflow#index"
  end

  scope "/users" do
    # Libraries
    resources :libraries, except: :show do
      collection { get "query" }
    end
  end

  # Static content
  get "static/cookies" => "static#cookies"
  post "static/echo" => "static#echo"
  get "static/user_data" => "static#user_data"

  # Static controller also is rendering files and images stored remotely
  get "file/*name" => "static#file", :format => false, :as => "static_file"
  get "manifest" => "static#manifest",
      :format => true,
      :constraints => {
        format: :json
      }
  get "browserconfig" => "static#browserconfig",
      :format => true,
      :constraints => {
        format: :xml
      }

  # unAPI service
  get "unapi" => "unapi#index"

  #
  # API v1
  #
  scope "api/v1", constraints: { format: :json } do
    get "lists/authors" => "lists#authors"
    get "lists/journals" => "lists#journals"
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

# Search and browse the document database
#
# This controller displays both traditional and advanced search pages and the
# resulting lists of documents.
#
# @see Sciveyor::Solr::Connection.search
class SearchController < ApplicationController
  # Show the main search index page
  #
  # @return [void]
  def index
    set_params
    render
  end

  # Show only the results table (for infinite scroll)
  #
  # @return [void]
  def load
    set_params
    render layout: false
  end

  # Show the advanced search page
  #
  # @return [void]
  def advanced
  end

  private

  # Set the parameters for running a search
  #
  # @return [void]
  def set_params
    @search_params =
      Sciveyor::Solr::Params.new(params: params, api: request.format != :html)

    @result = Sciveyor::Solr::Connection.search(@search_params.to_solr)
    @result_presenter =
      Sciveyor::Presenters::SearchResultPresenter.new(result: @result)
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
  # Return the text to put in the regular search box
  #
  # If we only have one field set, and it's dismax, then show it back to the
  # user like Google would. Otherwise, flag an advanced search.
  #
  # @return [String] the text to use as the search box value
  def search_box_value
    if params[:fields].blank? && params[:values].blank?
      ""
    elsif params[:fields]&.length == 1 && params[:fields][0] == "dismax" &&
          params[:values][0].present?
      params[:values][0]
    else
      I18n.t("search.index.adv_search_placeholder")
    end
  end

  # Return the fields you can choose from on the advanced search apge
  #
  # @return [Hash<String, Symbol>] a list of advanced search fields and
  #   their corresponding label strings
  def advanced_search_fields
    {
      I18n.t("search.advanced.dismax") => :dismax,
      I18n.t("search.advanced.fulltext") + " " +
        I18n.t("search.advanced.type_clean") =>
        :fullText_clean,
      I18n.t("search.advanced.fulltext") + " " +
        I18n.t("search.advanced.type_stem") =>
        :fullText_stem,
      I18n.t("search.advanced.fulltext") + " " +
        I18n.t("search.advanced.type_lem") =>
        :fullText_lem,
      Document.human_attribute_name(:title) + " " +
        I18n.t("search.advanced.type_clean") =>
        :title_clean,
      Document.human_attribute_name(:title) + " " +
        I18n.t("search.advanced.type_stem") =>
        :title_stem,
      Document.human_attribute_name(:title) + " " +
        I18n.t("search.advanced.type_lem") =>
        :title_lem,
      I18n.t("search.advanced.abstract") + " " +
        I18n.t("search.advanced.type_clean") =>
        :abstract_clean,
      I18n.t("search.advanced.abstract") + " " +
        I18n.t("search.advanced.type_stem") =>
        :abstract_stem,
      I18n.t("search.advanced.abstract") + " " +
        I18n.t("search.advanced.type_lem") =>
        :abstract_lem,
      Document.human_attribute_name(:authors) => :authors,
      Document.human_attribute_name(:journal) + " " +
        I18n.t("search.advanced.type_clean") =>
        :journal_clean,
      Document.human_attribute_name(:date) => :date,
      Document.human_attribute_name(:volume) => :volume,
      Document.human_attribute_name(:number) => :number,
      Document.human_attribute_name(:pages) => :pages
    }
  end

  # Get the list of facet links for one particular field
  #
  # This function takes the facets from the `Document` class, checks them
  # against the active facets, and creates a set of list items.
  #
  # @param [Sciveyor::Solr::Params] search_params current search parameters
  # @param [Sciveyor::Solr::Facets] facets the facets returned
  # @param [Symbol] field the field to return links for
  # @return [String] the built markup of addition links for this field
  def facet_addition_links(search_params, facets, field)
    # Get the facets for this field
    active_facets = facets.active(search_params)
    field_facets = (facets.sorted_for_field(field) - active_facets).take(5)

    # Build the return value
    tags =
      field_facets.map do |f|
        p = Sciveyor::Presenters::FacetPresenter.new(facet: f)

        new_facets = active_facets + [f]
        new_params =
          Sciveyor::Solr::Facets.search_params(search_params, new_facets)

        facet_add_link(new_params, f.hits.to_s, p.label)
      end

    safe_join(tags)
  end

  def facet_removal_links(search_params, facets)
    active_facets = facets&.active(search_params)
    tags = []

    # Remove all link
    if search_params.categories || search_params.facets
      remove_params = search_params.dup
      remove_params.categories = nil
      remove_params.facets = nil

      tags << facet_remove_link(
        remove_params,
        I18n.t("search.index.remove_all")
      )
    end

    active_facets&.each do |f|
      other_facets = active_facets.reject { |x| x == f }
      other_params =
        Sciveyor::Solr::Facets.search_params(search_params, other_facets)

      p = Sciveyor::Presenters::FacetPresenter.new(facet: f)
      tags << facet_remove_link(other_params, "#{p.field_label}: #{p.label}")
    end

    safe_join(tags)
  end

  def category_addition_tree(search_params, roots = Category.roots)
    tags =
      roots.map do |root|
        content_tag(:li) { category_add_link(search_params, root) }
      end

    safe_join(tags)
  end

  def category_removal_links(search_params)
    tags =
      Category
        .active(search_params)
        .map do |category|
          facet_remove_link(
            category.toggle_search_params(search_params),
            "#{Category.model_name.human}: #{category.name}"
          )
        end

    safe_join(tags)
  end

  private

  def facet_add_link(search_params, hits, label)
    link_to search_path(search_params.to_request), class: "nav-link" do
      hits =
        content_tag(
          :div,
          hits.to_s,
          class: "float-end badge bg-light text-dark mt-1"
        )

      safe_join([hits, label])
    end
  end

  def category_add_link(search_params, category)
    link =
      link_to search_path(
                category.toggle_search_params(search_params).to_request
              ),
              class: "nav-link" do
        contents = [
          check_box_tag(
            "category_#{category.to_param}",
            "1",
            category.enabled?(search_params),
            disabled: true
          ),
          category.name
        ]

        safe_join(contents)
      end

    tags = [link]
    if category.children.exists?
      tags << content_tag(
        :ul,
        category_addition_tree(search_params, category.children)
      )
    end

    safe_join(tags)
  end

  def facet_remove_link(search_params, label)
    link_to search_path(search_params.to_request), class: "nav-link" do
      close = content_tag(:div, close_icon, class: "float-end")

      safe_join([close, label])
    end
  end
end

app/views/search/_add.html.haml
.modal-dialog{role: "document"}
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      %h6.text-muted= t('.subheader')
      = close_icon('bs-dismiss': 'modal')
    - if current_user.datasets.blank?
      .modal-body
        %p= t('.no_datasets')
    - else
      = sciveyor_form_with url: dataset_path(current_user.datasets.first), method: :patch, html: { id: "add-form-#{document.id.html_id}" } do |form|
        = form.hidden_field :doc_id, value: document.id
        .modal-body
          = form.select :dataset_id, options_for_select(current_user.datasets_hash.transform_values { |d| d.uuid }), input_options: { class: 'search-add-select' }, label: Dataset.model_name.human
        .modal-footer
          = link_to t('common.cancel'), '#', class: 'btn btn-secondary', data: { bs_dismiss: 'modal' }
          = form.submit t('.submit'), color: 'btn-success'

app/views/search/_advanced_row.html.haml
.row.advanced-row.mb-3
  .col-3
    .form-floating.field-group
      = form.select 'fields[]', options_for_select(advanced_search_fields), {}, class: 'form-select'
      = form.label 'fields[]', t('.field_label')
  .col
    .form-floating.value-group
      = form.text_field 'values[]', class: 'form-control'
      = form.label 'values[]', t('.value_label')
  .col-auto
    .bool-group
      .btn-group
        = link_to '#', class: 'btn btn-outline-secondary advanced-add-button', type: 'button', aria: { label: t('.add_label') } do
          %i.fas.fa-plus
        = link_to '#', class: 'btn btn-outline-secondary advanced-remove-button invisible', type: 'button', aria: { label: t('.remove_label') } do
          %i.fas.fa-minus

app/views/search/_document.html.haml
%h5
  - if document.title
    = document.title
  - else
    = t('.untitled')
%p
  - if document.authors
    = document.authors.to_s
    |
  - if document.journal
    %em #{document.journal},
  - if document.volume
    = t('.volume_abbr', volume: document.volume) + ','
  - if document.number
    = t('.number_abbr', number: document.number)
  - if document.date
    = "(#{document.date.strftime('%Y')}),"
  - if document.pages
    = t('.pages_abbr', pages: document.pages)

app/views/search/_dropdown.html.haml
- if user_signed_in?
  %h6.dropdown-header= t('.dataset_header')
  = link_to t('.single_dataset'), new_dataset_path('q[]': "id:(\"#{document.id}\")"), class: 'dropdown-item ajax-modal', id: "single-#{document.id.html_id}"
  = link_to t('.add_to_dataset'), '#', class: 'dropdown-item', data: { bs_toggle: 'modal', bs_target: "#add-#{document.id.html_id}-modal" }
  .dropdown-divider
- if document.doi
  = link_to t('.journal'), "http://dx.doi.org/#{document.doi}", class: 'dropdown-item'
  .dropdown-divider
%h6.dropdown-header= t('.library')
- if user_signed_in?
  - current_user.libraries.each do |library|
    = link_to t('.yours') + ' ' + library.name, "#{library.url}#{Sciveyor::Documents::AsOpenUrl.new(document).params}", class: 'dropdown-item'
= link_to t('.worldcat'), "http://worldcatlibraries.org/registry/gateway?#{Sciveyor::Documents::AsOpenUrl.new(document).params}", class: 'dropdown-item'
= link_to t('.uk_openurl'), "http://openurl.ac.uk/?#{Sciveyor::Documents::AsOpenUrl.new(document).params}", class: 'dropdown-item'
.dropdown-divider
%h6.dropdown-header= t('.online')
- if document.title
  = link_to t('.google'), "http://scholar.google.com/scholar?q=#{CGI.escape(document.title)}", class: 'dropdown-item'
.dropdown-divider
%h6.dropdown-header= t('.details_header')
- if document.doi
  = link_to "DOI: #{document.doi}", "http://dx.doi.org/#{document.doi}", class: 'dropdown-item small'
%p.dropdown-wrap.small
  = t('.license', license: document.license || t('.no_license'))
- if document.licenseUrl
  = link_to t('.license_link'), document.licenseUrl, class: 'dropdown-item small'
%p.dropdown-wrap.small
  = t('.data_source', source: document.dataSource)
.dropdown-divider
%span.dropdown-item-text.small ID: #{document.id}

app/views/search/advanced.html.haml
- content_for :js_modules do
  = javascript_import_module_tag "search/advanced"
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  - if user_signed_in? && current_user.workflow_active
    %li.breadcrumb-item
      = link_to t('breadcrumbs.workflow_start'), workflow_start_path
    %li.breadcrumb-item
      = link_to t('breadcrumbs.workflow_info'), workflow_info_path(current_user.workflow_class)
    %li.breadcrumb-item
      = link_to t('breadcrumbs.workflow_activate'), workflow_activate_path(current_user.workflow_class)
  %li.breadcrumb-item= link_to t('breadcrumbs.search_index'), search_path
  %li.breadcrumb-item.active= t('breadcrumbs.search_advanced')
.row.mb-3
  .col-6
    %h1= t('.header')
    %h4.text-muted= t_md('.subheader_markdown')
.row.mb-5
  .col-12
    = form_with url: search_path, method: 'get', html: { role: 'form' } do |form|
      = javascript_tag("window.rlRowMarkup = '#{j render(partial: 'advanced_row', locals: { form: form })}';", nonce: true)
      .row.mb-4#advanced-rows
        = render partial: 'advanced_row', locals: { form: form }
      .row.mb-3
        .col-lg-6
          .form-floating
            = form.select :boolean, options_for_select([[t('.boolean_and'), :and], [t('.boolean_or'), :or]]), { include_blank: false }, class: 'form-select'
            = form.label :boolean, t('.boolean_label'), class: 'form-label'
      .row
        .col
          = form.submit t('.search_button'), class: 'btn btn-primary'
.row.advanced-solr
  .col-12.col-lg-6
    %button.btn.btn-secondary.btn-sm{
      type: "button",
      data: { bs_toggle: "collapse", bs_target: "#solr-collapse" },
      aria: { expanded: "false", controls: "solr-collapse" }
    }
      = t('.solr_header')
    .collapse#solr-collapse
      .card.card-body
        = sciveyor_form_with url: search_path, method: 'get' do |form|
          = form.text_area :solr, input_options: { escape: false }, label: t('.solr_label'), label_options: { class: 'visually-hidden' }
          = form.submit t('.solr_button')

app/views/search/index.html.haml
- content_for :js_modules do
  = javascript_import_module_tag "search/index"
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  - if user_signed_in? && current_user.workflow_active
    %l.breadcrumb-item
      = link_to t('breadcrumbs.workflow_start'), workflow_start_path
    %li.breadcrumb-item
      = link_to t('breadcrumbs.workflow_info'), workflow_info_path(current_user.workflow_class)
    %li.breadcrumb-item
      = link_to t('breadcrumbs.workflow_activate'), workflow_activate_path(current_user.workflow_class)
  %li.breadcrumb-item.active= t('breadcrumbs.search_index')
.row
  .col-7.col-lg-9
    = form_with url: search_path, method: :get, html: { role: 'form' } do |form|
      = form.hidden_field 'fields[]', value: 'dismax'
      - @search_params.facets&.each do |p|
        = form.hidden_field 'facets[]', value: p
      .mb-3
        %label.visually-hidden{for: "values[]"}= t('.placeholder')
        = form.search_field 'values[]', value: search_box_value, placeholder: t('.placeholder'), class: 'form-control'
      = form.submit t('.search_button'), class: 'visually-hidden'
  .col-5.col-lg-3
    .btn-group.d-flex{role: "group"}
      .btn-group.w-100{role: "group"}
        = link_to('#', class: 'btn btn-light w-100 dropdown-toggle', data: { bs_toggle: 'dropdown' }, role: 'button', aria: { haspopup: 'true', expanded: 'false' }) do
          %i.fas.fa-sort
          = t('.sort')
        .dropdown-menu
          - @result_presenter.sort_methods.each do |(param, desc)|
            - new_params = @search_params.dup
            - new_params.sort = param
            = link_to new_params.to_request, class: 'dropdown-item' do
              %span{class: (param == @search_params.sort ? nil : 'invisible')}
                \&check;
              = desc
      %a.btn.btn-light.w-100.d-lg-none.collapsed#filters-button{
        href: "#",
        role: "button",
        data: { bs_toggle: "collapse", bs_target: "#filters" }
      }
        %i.fas.fa-filter
        = t('.toggle_filters')
      = link_to user_signed_in? ? new_dataset_path(@search_params.to_dataset) : '#', class: "btn btn-success w-100 #{user_signed_in? ? 'ajax-modal' : 'disabled'}", id: 'new-dataset' do
        %i.fas.fa-save
        = t('.create_dataset')
.row
  .col-12.col-lg-3.order-lg-last
    %p.text-center= @result_presenter.num_hits_string
    .collapse.d-lg-block.mb-3#filters
      .card.bg-light.card-body
        - if @result.facets || Category.count
          %h4= t('.filter_header')
          %nav.nav.nav-pills.flex-column.filter-list
            - if @search_params.facets || @search_params.categories
              .filter-header= t('.active_filters')
              = facet_removal_links(@search_params, @result.facets)
              = category_removal_links(@search_params)
            - if @result.facets
              .filter-header= t('.author')
              = facet_addition_links(@search_params, @result.facets, :author)
              .filter-header= t('.journal')
              = facet_addition_links(@search_params, @result.facets, :journal)
              .filter-header= t('.date')
              = facet_addition_links(@search_params, @result.facets, :date)
            - if Category.count.positive?
              .filter-header= t('.categories')
              = category_addition_tree(@search_params)
        = link_to t('.advanced_search'), search_advanced_path, class: 'btn btn-outline-primary w-100'
  .col-12.col-lg-9.order-lg-first
    #scroller
      = render template: 'search/load', layout: false
.text-center.d-none#back-to-top
  = link_to t('.back_to_top'), '#', class: 'btn btn-info btn-sm'

app/views/search/load.html.haml
%table.table.table-striped.document-list
  - @result.documents.each do |d|
    %tr
      %td
        %abbr.unapi-id{title: d.id}= ''
        .dropdown.float-end
          %button.btn.btn-outline-secondary.btn-sm.ms-1.mb-1.dropdown-toggle{
            type: "button",
            id: "drop-#{d.id.html_id}",
            data: { bs_toggle: "dropdown" },
            aria: { haspopup: "true", expanded: "false" }
          }
            = t('.dropdown_button')
          .dropdown-menu.dropdown-menu-end.document-dropdown{
            aria: { labelledby: "drop-#{d.id.html_id}" }
          }
            = render partial: 'dropdown', locals: { document: d }
        = render partial: 'document', locals: { document: d }
        -# The modal dialog box for adding this document to an existing dataset needs to be outside the dropdown menu
        - if user_signed_in?
          -# FIXME: this should probably have the fade class?
          .modal{
            id: "add-#{d.id.html_id}-modal",
            tabindex: "-1",
            role: "dialog",
            aria: { hidden: "true" }
          }
            = render partial: 'add', locals: { document: d }
  - if @result_presenter.next_page_params(@search_params)
    %tr.scroll-pagination
      %td.text-center
        = link_to t('.more_hits'), search_path(@result_presenter.next_page_params(@search_params).to_request), class: 'scroll-next-page'