config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get "workflow" => "workflow#index"
  get "workflow/start" => "workflow#start"
  get "workflow/stop" => "workflow#stop"
  get "workflow/info/:class" => "workflow#info",
      :as => "workflow_info",
      :constraints => {
        class: /[A-Z][A-Za-z]+/
      }
  get "workflow/activate/:class" => "workflow#activate",
      :as => "workflow_activate",
      :constraints => {
        class: /[A-Z][A-Za-z]+/
      }
  get "workflow/options/:class" => "workflow#options",
      :as => "workflow_options",
      :constrants => {
        class: /[A-Z][A-Za-z]+/
      }
  post "workflow/run/:class" => "workflow#run",
       :as => "workflow_run",
       :constraints => {
         class: /[A-Z][A-Za-z]+/
       }
  get "workflow/fetch" => "workflow#fetch"
  get "workflow/fetch_load" => "workflow#fetch_load"
  delete "workflow/:id" => "workflow#destroy", :as => :destroy_task
  get "workflow/:id/view/:template" => "workflow#view", :as => :view_task

  # Start off on the landing/dashboard page
  root to: "workflow#index"

  # Search/Browse page
  get "search" => "search#index"
  get "search/load" => "search#load"
  get "search/advanced" => "search#advanced"

  # Documents
  get "documents/:id/export" => "documents#export",
      :as => "documents_export",
      :constraints => {
        id: /.*/
      }

  # Datasets
  resources :datasets, except: :edit do
    collection { get "load" }
  end

  # User login routes
  devise_for :users, skip: [:sessions], controllers: { passwords: "passwords" }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post "users/sign_in" => "devise/sessions#create", :as => :user_session
    match "users/sign_out" => "devise/sessions#destroy",
          :as => :destroy_user_session,
          :via => Devise.mappings[:user].sign_out_via

    # User export manipulation
    get "users/export" => "users#export_create", :as => :user_export
    delete "users/export" => "users#export_delete", :as => ""

    # Redirect to the root after a successful user edit
    get "users" => "workflow#index"
  end

  scope "/users" do
    # Libraries
    resources :libraries, except: :show do
      collection { get "query" }
    end
  end

  # Static content
  get "static/cookies" => "static#cookies"
  post "static/echo" => "static#echo"
  get "static/user_data" => "static#user_data"

  # Static controller also is rendering files and images stored remotely
  get "file/*name" => "static#file", :format => false, :as => "static_file"
  get "manifest" => "static#manifest",
      :format => true,
      :constraints => {
        format: :json
      }
  get "browserconfig" => "static#browserconfig",
      :format => true,
      :constraints => {
        format: :xml
      }

  # unAPI service
  get "unapi" => "unapi#index"

  #
  # API v1
  #
  scope "api/v1", constraints: { format: :json } do
    get "lists/authors" => "lists#authors"
    get "lists/journals" => "lists#journals"
  end
end

app/models/library.rb
# frozen_string_literal: true

# Representation of a library-owned OpenURL resolver
#
# @!attribute name
#   @raise [RecordInvalid] if the name is missing (validates :presence)
#   @return [String] The name of the library
# @!attribute url
#   @raise [RecordInvalid] if the URL is missing (validates :presence)
#   @raise [RecordInvalid] if the URL is not a valid URL (validates :format)
#   @return [String] The base URL for its OpenURL resolver
# @!attribute user
#   @raise [RecordInvalid] if the user is missing (validates :presence)
#   @return [User] The user this library record belongs to
class Library < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :url,
            presence: true,
            format: {
              with: %r{\A(https?)://[^\s/$.?#].[^\s]*\z}i
            }
  validates :user_id, presence: true

  before_validation do |library|
    library.url = "http://" + (url || "") unless library.url&.include?("://")
  end

  after_validation do |library|
    library.url << "?" unless library.url&.end_with?("?")
  end

  # @return [String] string representation of this library
  def to_s
    name
  end
end

app/controllers/libraries_controller.rb
# frozen_string_literal: true

# Work with the library records belonging to a given user
#
# This controller is responsible for the handling of the library OpenURL
# resolvers that users are allowed to link to their accounts.
#
# @see Library
class LibrariesController < ApplicationController
  before_action :authenticate_user!

  # Display the list of the user's libraries
  #
  # @return [void]
  def index
    render layout: false
  end

  # Show the form for creating a new library link
  #
  # @return [void]
  def new
    @library = current_user.libraries.build
    render layout: false
  end

  # Show the form for editing a library link
  #
  # @return [void]
  def edit
    @library = current_user.libraries.find(params[:id])
    render layout: false
  end

  # Create a new library link in the database
  #
  # @return [void]
  def create
    @library = current_user.libraries.new(library_params)
    if @library.save
      Rails.logger.info(
        short_message: "Created library",
        _method: "libraries#create",
        _user_id: current_user.id,
        _library_id: @library.id,
        _url: @library.url
      )

      redirect_to edit_user_registration_path,
                  flash: {
                    success: I18n.t("libraries.create.success")
                  }
    else
      render action: "new", layout: false
    end
  end

  # Update the attributes of a library link in the database
  #
  # @return [void]
  def update
    @library = current_user.libraries.find(params[:id])

    if @library.update(library_params)
      current_user.libraries.reload

      Rails.logger.info(
        short_message: "Edited library",
        _method: "libraries#update",
        _user_id: current_user.id,
        _library_id: @library.id,
        _url: @library.url
      )

      redirect_to edit_user_registration_path,
                  flash: {
                    success: I18n.t("libraries.update.success")
                  }
    else
      render action: "edit", layout: false
    end
  end

  # Delete a library link from the database
  #
  # @return [void]
  def destroy
    @library = current_user.libraries.find(params[:id])

    @library.destroy
    current_user.libraries.reload

    Rails.logger.info(
      short_message: "Deleted library",
      _method: "libraries#destroy",
      _user_id: current_user.id,
      _library_id: @library.id
    )

    redirect_to edit_user_registration_path
  end

  # Query the list of available libraries from OCLC
  #
  # This function sets `@libraries` to the list of all available libraries
  # for the client's IP address, according to the WorldCat library database.
  #
  # @return [void]
  def query
    @libraries = []

    begin
      res =
        Net::HTTP.start("www.worldcat.org") do |http|
          http.get("/registry/lookup?IP=#{request.remote_ip}")
        end

      # We have to strip the namespaces from this XML, because the markup we
      # get from WorldCat often includes anonymous, unprefixed namespaces
      # on child elements, which drives Nokogiri absolutely crazy.
      doc = Nokogiri::XML::Document.parse(res.body).remove_namespaces!
      @libraries =
        doc
          .css("resolverRegistryEntry")
          .map do |entry|
            {
              name: entry.at_css("institutionName").content,
              url: entry.at_css("resolver baseURL").content
            }
          end

      Rails.logger.info(
        short_message: "Queried local libraries for user",
        _method: "libraries#query",
        _user_id: current_user.id,
        _count: @libraries.count
      )
    rescue *Net::HTTP::EXCEPTIONS
      @libraries = []
    end

    render layout: false
  end

  private

  # Whitelist acceptable library parameters
  #
  # @return [ActionController::Parameters] acceptable parameters for
  #   mass-assignment
  def library_params
    params.require(:library).permit(:name, :url)
  end
end

app/views/libraries/_form.html.haml
= sciveyor_form_with model: library, url: url, html: { novalidate: true, class: 'needs-validation' } do |form|
  .modal-body
    = form.text_field :name, input_options: { required: true, autofocus: true }
    = form.text_field :url, input_options: { required: true }
  .modal-footer
    = link_to t('common.cancel'), '#', class: 'btn btn-secondary', data: { bs_dismiss: 'modal' }
    = form.submit

app/views/libraries/edit.html.haml
.modal-dialog{role: "document"}
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      %h6.text-muted= t('.subheader')
      = close_icon('bs-dismiss': 'modal')
    = render partial: 'form', locals: { library: @library, url: library_path(@library) }

app/views/libraries/index.html.haml
.btn-group
  = link_to t('.query'), query_libraries_path, class: 'btn btn-secondary btn-sm ajax-modal', id: 'query-libraries'
  = link_to t('.add_new'), new_library_path, class: 'btn btn-secondary btn-sm ajax-modal', id: 'new-library'
%table.table.button-table.table-striped
  %thead
    %tr
      %th.label-cell= t('.name_column')
      %th.button-cell
  %tbody
    - current_user.libraries.each_with_index do |library, i|
      %tr
        %td.label-cell= library.name
        %td.button-cell
          = link_to t('.edit_button'), edit_library_path(library), class: 'btn btn-sm btn-secondary ajax-modal', id: "edit-library-#{i}"
          = link_to t('.delete_button'), library_path(library), method: 'delete', data: { confirm: t('.delete_confirm') }, class: 'btn btn-sm btn-danger'
    - if current_user.libraries.empty?
      %tr
        %td.label-cell= t('.no_libraries')
        %td.button-cell

app/views/libraries/new.html.haml
.modal-dialog{role: "document"}
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      %h6.text-muted= t('.subheader')
      = close_icon('bs-dismiss': 'modal')
    = render partial: 'form', locals: { library: @library, url: libraries_path }

app/views/libraries/query.html.haml
.modal-dialog{role: "document"}
  .modal-content
    .modal-header
      %h4.modal-title= t('.header')
      %h6.text-muted= t('.subheader')
      = close_icon('bs-dismiss': 'modal')
    .modal-body
      - if @libraries.empty?
        %p= t('.no_libraries')
      - else
        - @libraries.each do |library|
          = form_with url: libraries_path, method: :post do |form|
            = form.hidden_field 'library[name]', value: library[:name]
            = form.hidden_field 'library[url]', value: library[:url]
            = form.submit library[:name], class: 'button small secondary'
    .modal-footer
      %button.btn.btn-secondary{data: { bs_dismiss: "modal" }}
        = t('common.cancel')