config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # The user workflow
  get "workflow" => "workflow#index"
  get "workflow/start" => "workflow#start"
  get "workflow/stop" => "workflow#stop"
  get "workflow/info/:class" => "workflow#info",
      :as => "workflow_info",
      :constraints => {
        class: /[A-Z][A-Za-z]+/
      }
  get "workflow/activate/:class" => "workflow#activate",
      :as => "workflow_activate",
      :constraints => {
        class: /[A-Z][A-Za-z]+/
      }
  get "workflow/options/:class" => "workflow#options",
      :as => "workflow_options",
      :constrants => {
        class: /[A-Z][A-Za-z]+/
      }
  post "workflow/run/:class" => "workflow#run",
       :as => "workflow_run",
       :constraints => {
         class: /[A-Z][A-Za-z]+/
       }
  get "workflow/fetch" => "workflow#fetch"
  get "workflow/fetch_load" => "workflow#fetch_load"
  delete "workflow/:id" => "workflow#destroy", :as => :destroy_task
  get "workflow/:id/view/:template" => "workflow#view", :as => :view_task

  # Start off on the landing/dashboard page
  root to: "workflow#index"

  # Search/Browse page
  get "search" => "search#index"
  get "search/load" => "search#load"
  get "search/advanced" => "search#advanced"

  # Documents
  get "documents/:id/export" => "documents#export",
      :as => "documents_export",
      :constraints => {
        id: /.*/
      }

  # Datasets
  resources :datasets, except: :edit do
    collection { get "load" }
  end

  # User login routes
  devise_for :users, skip: [:sessions], controllers: { passwords: "passwords" }
  devise_scope :user do
    # We only want users to sign in using the dropdown box on the main page,
    # not by visiting /users/sign_in, so we don't create a get 'sign_in' route
    # here.
    post "users/sign_in" => "devise/sessions#create", :as => :user_session
    match "users/sign_out" => "devise/sessions#destroy",
          :as => :destroy_user_session,
          :via => Devise.mappings[:user].sign_out_via

    # User export manipulation
    get "users/export" => "users#export_create", :as => :user_export
    delete "users/export" => "users#export_delete", :as => ""

    # Redirect to the root after a successful user edit
    get "users" => "workflow#index"
  end

  scope "/users" do
    # Libraries
    resources :libraries, except: :show do
      collection { get "query" }
    end
  end

  # Static content
  get "static/cookies" => "static#cookies"
  post "static/echo" => "static#echo"
  get "static/user_data" => "static#user_data"

  # Static controller also is rendering files and images stored remotely
  get "file/*name" => "static#file", :format => false, :as => "static_file"
  get "manifest" => "static#manifest",
      :format => true,
      :constraints => {
        format: :json
      }
  get "browserconfig" => "static#browserconfig",
      :format => true,
      :constraints => {
        format: :xml
      }

  # unAPI service
  get "unapi" => "unapi#index"

  #
  # API v1
  #
  scope "api/v1", constraints: { format: :json } do
    get "lists/authors" => "lists#authors"
    get "lists/journals" => "lists#journals"
  end
end

app/controllers/workflow_controller.rb
# frozen_string_literal: true

# Display the user's workflow through Sciveyor
#
# We walk the user through the process of logging in, selecting an analysis
# type to run, gathering datasets, and collecting results.  This controller
# is responsible for all of that.
class WorkflowController < ApplicationController
  layout "full_page"
  before_action :authenticate_user!, except: :index

  # Show the introduction page or the user dashboard
  #
  # @return [void]
  def index
    @database_size = Sciveyor::Solr::CorpusStats.new.size || 0

    if user_signed_in?
      render "dashboard"
    else
      render "index"
    end
  end

  # Start running a new analysis
  #
  # @return [void]
  def start
  end

  # Destroy the currently building analysis, leaving workflow mode
  #
  # @return [void]
  def stop
    current_user.workflow_active = false
    current_user.workflow_class = nil
    current_user.workflow_datasets.clear
    current_user.save

    redirect_to workflow_path, alert: I18n.t("workflow.stop.success")
  end

  # Show information about a job
  #
  # @return [void]
  def info
    set_workflow_parameters
  end

  # Get the user to collect datasets for a job
  #
  # @return [void]
  def activate
    set_workflow_parameters

    # Write out the class that the user has chosen
    current_user.workflow_active = true
    current_user.workflow_class = params[:class]

    # See if we've been asked to link or unlink a dataset to this job
    if params[:link_dataset_id]
      # Make sure the dataset exists
      dataset = Dataset.find_by!(uuid: params[:link_dataset_id])
      current_user.workflow_datasets << dataset.uuid
    elsif params[:unlink_dataset_id]
      current_user.workflow_datasets.delete(params[:unlink_dataset_id])
    end

    # Save our changes, if any, and update the workflow parameters
    current_user.save!
    set_workflow_parameters
  end

  # Get the configuration of the job from the user
  #
  # This renders the `_params.html.haml` view from inside the selected job.
  #
  # @return [void]
  def options
    set_workflow_parameters

    # Make sure we've linked enough datasets
    return if current_user.workflow_datasets.size == @klass.num_datasets

    raise ArgumentError,
          "incorrect number of datasets specified for #{params[:class]}"
  end

  # Perform the task that the user has selected
  #
  # @return [void]
  def run
    set_workflow_parameters

    # Create a task
    task =
      current_user.tasks.create(
        name: @klass.t(".short_desc"),
        type: params[:class],
        datasets:
          current_user.workflow_datasets.map { |id| Dataset.find_by!(uuid: id) }
      )

    # Start it up
    task.job_start(@job_params || {})

    current_user.workflow_active = false
    current_user.workflow_class = nil
    current_user.workflow_datasets.clear
    current_user.save

    redirect_to root_path, flash: { success: I18n.t("workflow.run.finished") }
  end

  # Allow the user to pick up data from all of their tasks
  #
  # @return [void]
  def fetch
    set_fetch_parameters

    if params[:terminate]
      # Delete all unfinished tasks in the DB.
      current_user.tasks.active.readonly(false).destroy_all
      redirect_to root_path, alert: I18n.t("workflow.fetch.terminate")
      return
    end

    render
  end

  # Show the results display only for quick updates
  #
  # @return [void]
  def fetch_load
    disable_browser_cache
    set_fetch_parameters

    render layout: false
  end

  # Delete a task
  #
  # This action deletes a given task and its associated files.
  #
  # @return [void]
  def destroy
    current_user.tasks.find(params[:id]).destroy
    redirect_to workflow_fetch_path,
                flash: {
                  success: I18n.t("workflow.destroy.success")
                }
  end

  # Show a view from a task
  #
  # This action will render a view that comes packaged with a background job.
  #
  # @return [void]
  def view
    task = current_user.tasks.find(params[:id])
    presenter = Sciveyor::Presenters::TaskPresenter.new(task: task)

    render(
      task.template_path(params[:template]),
      formats: [(params[:format] || :html).to_sym],
      locals: {
        task: task,
        presenter: presenter,
        klass: task.job_class
      }
    )
  end

  private

  # Get the current workflow details from the params
  #
  # @return [void]
  def set_workflow_parameters
    raise ActiveRecord::RecordNotFound unless params[:class]
    @klass = Task.job_class(params[:class])

    @num_datasets = @klass.num_datasets
    @num_workflow_datasets = current_user.workflow_datasets.size

    @job_params = params[:job_params]&.to_unsafe_h&.with_indifferent_access
  end

  # Get the parameters for fetching workflow tasks
  #
  # @return [void]
  def set_fetch_parameters
    tasks = current_user.tasks

    @pending_tasks = tasks.active.order(:created_at)
    @finished_tasks = tasks.finished.order(finished_at: :desc)
  end
end

app/views/workflow/activate.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item
    = link_to t('breadcrumbs.workflow_start'), workflow_start_path
  %li.breadcrumb-item
    = link_to t('breadcrumbs.workflow_info'), workflow_info_path(params[:class])
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_activate')
.row
  .col-12
    %h1= t('.header')
    - if @num_workflow_datasets < @num_datasets
      %h4.text-muted= t('.subheader_pending')
    - else
      %h4.text-muted= t('.subheader_done')
- if @num_workflow_datasets < @num_datasets
  .row
    .col-12
      %p= t('.pending_instructions', count: @num_datasets)
.row
  .col-12
    %h3= t('.dataset_list')
    - if @num_workflow_datasets < @num_datasets
      .alert.alert-danger{role: "alert"}
        = t('.pending_count', count: (@num_datasets - @num_workflow_datasets))
    %table.table.button-table.table-striped
      %thead
        %tr
          %th.label-cell= t('.name_column')
          %th.button-cell
      %tbody
        - if @num_workflow_datasets.zero?
          %tr
            %td.label-cell= t('.no_datasets')
            %td.button-cell
        - else
          - current_user.workflow_datasets.each do |uuid|
            - d = Dataset.find_by!(uuid: uuid)
            %tr
              %td.label-cell= d.name_for(current_user)
              %td.button-cell
                = link_to t('.delete_button'), workflow_activate_path(params[:class], unlink_dataset_id: d.uuid), data: { confirm: t('.delete_confirm') }, class: 'btn btn-sm btn-danger'
- if @num_workflow_datasets < @num_datasets
  .row
    .col-12
      .btn-group
        = link_to t('.create_button'), search_path, class: 'btn btn-success'
        = link_to t('.link_button'), '#', data: { bs_toggle: 'modal', bs_target: '#link-modal' }, class: 'btn btn-secondary'
- else
  .row.activate-pad
    .col-12.col-lg-6.offset-lg-3
      - if lookup_context.exists?('params', "jobs/#{params[:class].underscore}", true)
        = link_to t('.button_params'), workflow_options_path(class: params[:class]), class: 'btn btn-primary w-100'
      - else
        = form_with url: workflow_run_path(class: params[:class]) do |form|
          = form.submit t('.button_start'), class: 'btn btn-success w-100'
-# FIXME: this should probably have the fade class?
.modal#link-modal{tabindex: "-1", role: "dialog", aria: { hidden: "true" }}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h4.modal-title= t('.link_header')
        %h6.text-muted= t('.link_subheader')
        = close_icon('bs-dismiss': 'modal')
      - if current_user.datasets.empty?
        .modal-body
          %p= t('.link_no_datasets')
        .modal-footer
          %button.btn.btn-secondary{data: { bs_dismiss: "modal" }}
            = t('common.cancel')
      - else
        = sciveyor_form_with url: workflow_activate_path(params[:class]), method: :get do |form|
          .modal-body
            = form.select :link_dataset_id, options_for_select(current_user.datasets_hash.transform_values { |d| d.uuid }), label: Dataset.model_name.human
          .modal-footer
            = link_to t('common.cancel'), '#', class: 'btn btn-secondary', data: { bs_dismiss: 'modal' }
            = form.submit t('.link_submit'), color: 'btn-success'

app/views/workflow/dashboard.html.haml
.row
  .col-9.offset-1
    %h1= t('.header', app_name: 'Sciveyor')
    %h4.text-muted= t('.subheader', app_name: 'Sciveyor')
.row.dashboard
  .col-4.offset-1
    = link_to t('.start_button'), workflow_start_path, class: 'btn btn-success w-100'
    %p= t('.start_explanation')
  .col-4
    = link_to t('.fetch_button'), workflow_fetch_path, class: 'btn btn-secondary w-100'
    %p= t('.fetch_explanation')
.row.dashboard
  .col-4.offset-3
    = link_to t('.advanced_button'), search_path, class: 'btn btn-secondary w-100'
    %p= t('.advanced_explanation')

app/views/workflow/fetch.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_fetch')
.row
  .col-12
    %h1= t('.header')
    %h4.text-muted= t('.subheader')
.row
  .col-12#workflow-task-list{
    data: { sv_fetch: "auto", sv_fetch_url: workflow_fetch_load_path }
  }
    = render template: 'workflow/fetch_load', layout: false

app/views/workflow/fetch_load.html.haml
.row
  .col-12
    %h4= t('.pending_header')
    - if @pending_tasks.empty?
      %p= t('.no_pending')
    - else
      %table.table.button-table.table-striped#pending-table
        %thead
          %tr
            %th.label-cell= t('.task_column')
            %th.label-cell= Dataset.model_name.human
        %tbody
          - @pending_tasks.each do |t|
            - p = Sciveyor::Presenters::TaskPresenter.new(task: t)
            %tr
              %td.label-cell= t.name
              %td.label-cell= p.dataset_list
      .card.text-white.bg-secondary.card-body
        %p.card-text
          = t_md('.pending_cancel_markdown', terminate_url: workflow_fetch_path(terminate: 'true'))
.row
  .col-12
    %h4= t('.completed_header')
    - if @finished_tasks.empty?
      %p= t('.no_completed')
    - else
      %table.table.button-table.table-striped#finished-table
        %thead
          %tr
            %th.label-cell= t('.task_column')
            %th.label-cell= Dataset.model_name.human
            %th.label-cell= t('.finished_column')
            %th.button-cell= t('.results_column')
        %tbody
          - @finished_tasks.each do |task|
            - p = Sciveyor::Presenters::TaskPresenter.new(task: task)
            %tr
              %td.label-cell= task.name
              %td.label-cell= p.dataset_list
              %td.label-cell
                = task.failed ? t('common.progress.failure') : l(task.finished_at, format: :short)
              - if task.failed
                %td.button-cell
                  = link_to t('.delete_button'), destroy_task_path(task), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: t('.delete_confirm') }
              - else
                %td.button-cell
                  - if lookup_context.exists?(task.template_path('results'))
                    = link_to t('.view_button'), view_task_path(task, template: 'results'), class: 'btn btn-sm btn-success'
                  -# Render a single button for the download if there's only one, or render a dropdown button if there's multiple uploads
                  - if task.uploads.downloadable.count == 1
                    = link_to t('.download_button'), static_file_path(task.uploads.downloadable.first.filename), class: 'btn btn-sm btn-success'
                  - elsif task.uploads.downloadable.count > 1
                    .btn-group
                      = link_to t('.download_button'), '#', class: 'btn btn-sm btn-success dropdown-toggle', data: { bs_toggle: 'dropdown' }, role: 'button', aria: { haspopup: 'true', expanded: 'false' }
                      .dropdown-menu
                        - task.uploads.downloadable.each do |f|
                          = link_to "#{f.description} (#{f.short_description})", static_file_path(f.filename), class: 'dropdown-item'
                  = link_to t('.delete_button'), destroy_task_path(task), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: t('.delete_confirm') }

app/views/workflow/index.html.haml
.row
  .col-8.offset-2#markdown-landing
    = image_tag 'landing-logo.svg'
    %h4= t('.intro_header')
    %blockquote
      %h5= t('.questions_header')
      %p
        = t('.question_one')
        %br
        = t('.question_two')
        %br
        =t ('.question_three')
    %h3= t('.answer_header')
    %p= t('.answer_description')
.row
  .col-4.offset-4#landing-login
    = link_to t('.sign_up_button'), new_user_registration_path, class: 'btn btn-primary btn-lg w-100'
.row
  .col-6.offset-3
    .carousel.carousel-dark.slide#screenshot-carousel{
      data: { bs_ride: "carousel" }
    }
      .carousel-inner
        .carousel-item.active
          = image_tag 'screenshot-one.jpg', class: 'd-block w-100'
          .carousel-caption.d-none.d-md-block
            %p= t('.caption_one')
        .carousel-item
          = image_tag 'screenshot-two.jpg', class: 'd-block w-100'
          .carousel-caption.d-none.d-md-block
            %p= t('.caption_two')
        .carousel-item
          = image_tag 'screenshot-three.jpg', class: 'd-block w-100'
          .carousel-caption.d-none.d-md-block
            %p= t('.caption_three')
      %button.carousel-control-prev{
        type: "button",
        data: { bs_target: "#screenshot-carousel", bs_slide: "prev" }
      }
        %span.carousel-control-prev-icon{aria: { hidden: "true" }}
        %span.visually-hidden Previous
      %button.carousel-control-next{
        type: "button",
        data: { bs_target: "#screenshot-carousel", bs_slide: "next" }
      }
        %span.carousel-control-next-icon{aria: { hidden: "true" }}
        %span.visually-hidden Next

app/views/workflow/info.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item
    = link_to t('breadcrumbs.workflow_start'), workflow_start_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_info')
.row
  .col-12.col-lg-6.offset-lg-6
    .btn-group.d-flex{role: "group"}
      = link_to t('.back'), workflow_start_path, class: 'btn btn-secondary w-100'
      = link_to t('.start'), workflow_activate_path(params[:class]), class: 'btn btn-success w-100'
.row
  .col-12#markdown-info
    = render partial: "jobs/#{@klass.name.demodulize.underscore}/info"
.row
  .col-12.col-lg-6.offset-lg-6
    .btn-group.d-flex{role: "group"}
      = link_to t('.back'), workflow_start_path, class: 'btn btn-secondary w-100'
      = link_to t('.start'), workflow_activate_path(params[:class]), class: 'btn btn-success w-100'

app/views/workflow/options.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item
    = link_to t('breadcrumbs.workflow_start'), workflow_start_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_options')
.row.mb-3
  .col-12
    %h1= t('.header')
    %h4.text-muted= t('.subheader')
.row
  .col-12.col-lg-6
    = render partial: "jobs/#{@klass.name.demodulize.underscore}/params"

app/views/workflow/start.html.haml
- content_for :breadcrumbs do
  %li.breadcrumb-item= link_to t('breadcrumbs.root'), root_path
  %li.breadcrumb-item.active= t('breadcrumbs.workflow_start')
.row
  .col-12
    %h1= t('.header')
    %h4.text-muted= t('.subheader')
- Task.job_list.each do |klass|
  - next unless klass.available?
  .row.questions
    .col-12
      = link_to simple_format(klass.t('.question'), {}, wrapper_tag: 'span'), workflow_info_path(klass.name.demodulize.to_s), class: 'btn btn-secondary w-100'